name: Branch created
on:
  push:
    branches:
      - '*'
    tags:
      - "!*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check branch created
        run: echo $GITHUB_REF_NAME